---
- hosts: server
  gather_facts: false
  tasks:
    - name: kill all python process
      shell: kill -9 $(ps aux | grep -v grep | grep 'python3 run_test.py --file_path' | awk '{ print $2 }')
