---
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Install basic list of packages
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      state: present
      update_cache: yes

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker packages
    apt:
      name: ['docker-ce','docker-ce-cli','containerd.io']
      state: present

  - name: install certain python modules for docker
    pip:
      name: "{{ item.name }}"
      state: present
    with_items:
    - { name: docker-py }

  - name: Add qateam user to docker group
    user:
      name: qateam
      groups: docker
      append: yes

  - name: 'set periodic docker system prune'
    cron:
      name: 'docker-prune'
      minute: '0'
      hour: '*/2'
      job: 'docker container prune -f'

  - user: name={{ansible_user}} groups=input
  - name: reset ssh connection
    meta: reset_connection
