---
- hosts: server
  gather_facts: false
  tasks:
    - name: Stop all rcd_test container.
      shell: "docker ps -q -f name=rcd_ecdhe* | xargs --no-run-if-empty docker stop"

    - name: Remove all rcd_test container.
      shell: "docker ps -a -q -f name=rcd_ecdhe* | xargs --no-run-if-empty docker rm"

